# Generated by Django 5.0.4 on 2024-05-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='alumni',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
