# Generated by Django 5.0.4 on 2024-05-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alumni_firstname_alumni_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventsName', models.CharField(max_length=100)),
                ('eventsDate', models.DateField()),
                ('eventsLocation', models.CharField(max_length=100)),
                ('eventsDescription', models.TextField()),
                ('eventsImage', models.ImageField(blank=True, null=True, upload_to='event_images/')),
            ],
        ),
    ]
