# Generated by Django 5.0.4 on 2024-05-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventsDate',
            field=models.CharField(max_length=100),
        ),
    ]
