# Generated by Django 5.0.4 on 2024-05-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_event_eventsdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='eventID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
