# Generated by Django 5.0.4 on 2024-05-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_event_id_event_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
