# Generated by Django 5.0.4 on 2024-05-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_event_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventsDate',
            field=models.DateField(),
        ),
    ]
