# Generated by Django 5.0.4 on 2024-05-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_event_eventsdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFair',
            fields=[
                ('jobfair_id', models.AutoField(primary_key=True, serialize=False)),
                ('jobdescription', models.CharField(max_length=255)),
                ('companyname', models.CharField(max_length=255)),
                ('joblocation', models.CharField(max_length=255)),
                ('employmenttype', models.CharField(max_length=100)),
                ('jobreqone', models.TextField()),
                ('jobreqtwo', models.TextField(blank=True, null=True)),
                ('jobreqthree', models.TextField(blank=True, null=True)),
                ('jobreqfour', models.TextField(blank=True, null=True)),
                ('jobreqfive', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
