# Generated by Django 5.0.4 on 2024-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_jobfair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfair',
            name='jobreqfive',
        ),
        migrations.RemoveField(
            model_name='jobfair',
            name='jobreqfour',
        ),
        migrations.RemoveField(
            model_name='jobfair',
            name='jobreqone',
        ),
        migrations.RemoveField(
            model_name='jobfair',
            name='jobreqthree',
        ),
        migrations.RemoveField(
            model_name='jobfair',
            name='jobreqtwo',
        ),
        migrations.AddField(
            model_name='jobfair',
            name='jobtitle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobfair',
            name='jobdescription',
            field=models.TextField(),
        ),
    ]
