# Generated by Django 5.0.4 on 2024-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_jobfair_jobreqfive_remove_jobfair_jobreqfour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfair',
            name='jobsalary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
