# Generated by Django 5.0.4 on 2024-05-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_jobfair_jobsalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfair',
            name='jobsalary',
            field=models.CharField(max_length=255),
        ),
    ]
