# Generated by Django 5.0.4 on 2024-05-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_jobfair_jobsalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yearbook',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('yearbookFirstname', models.CharField(max_length=100)),
                ('yearbookLastname', models.CharField(max_length=100)),
                ('yearbookAddress', models.CharField(max_length=255)),
                ('yearbookCourse', models.CharField(max_length=100)),
                ('yearbookImage', models.ImageField(upload_to='yearbook_images/')),
            ],
        ),
    ]
