# Generated by Django 5.0.4 on 2024-05-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_yearbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearbook',
            old_name='entry_id',
            new_name='yearbbokID',
        ),
    ]
