# Generated by Django 5.0.4 on 2024-05-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_entry_id_yearbook_yearbbokid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearbook',
            old_name='yearbbokID',
            new_name='yearbookID',
        ),
    ]
