# Generated by Django 5.0.4 on 2024-05-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_yearbbokid_yearbook_yearbookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbook',
            name='yearbookGender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
