# Generated by Django 5.0.4 on 2024-05-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_yearbook_yearbookgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbook',
            name='yearbookYearGrad',
            field=models.IntegerField(default=0),
        ),
    ]
