# Generated by Django 5.0.4 on 2024-05-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_yearbook_yearbookyeargrad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduateform',
            old_name='id',
            new_name='graduatedID',
        ),
    ]
