# Generated by Django 5.0.4 on 2024-05-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_id_graduateform_graduatedid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduateform',
            old_name='graduatedID',
            new_name='alumniID',
        ),
    ]
