# Generated by Django 5.0.4 on 2024-05-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_graduatedid_graduateform_alumniid'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateform',
            name='studentID',
            field=models.IntegerField(default=0),
        ),
    ]
