# Generated by Django 5.0.4 on 2024-05-20 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_graduateform_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduateform',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='graduateform',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='graduateform',
            name='city',
        ),
        migrations.RemoveField(
            model_name='graduateform',
            name='civilstatus',
        ),
        migrations.RemoveField(
            model_name='graduateform',
            name='collegedegree',
        ),
        migrations.RemoveField(
            model_name='graduateform',
            name='country',
        ),
        migrations.RemoveField(
            model_name='graduateform',
            name='degreefinished',
        ),
        migrations.RemoveField(
            model_name='graduateform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='graduateform',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='graduateform',
            name='mobilenumber',
        ),
        migrations.RemoveField(
            model_name='graduateform',
            name='peruniversity',
        ),
        migrations.RemoveField(
            model_name='graduateform',
            name='postalcode',
        ),
        migrations.RemoveField(
            model_name='graduateform',
            name='province',
        ),
    ]
