# Generated by Django 5.0.4 on 2024-05-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_graduateform_address2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduateform',
            name='studentID',
        ),
    ]
