# Generated by Django 5.0.4 on 2024-05-20 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_graduateform_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateform',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
