# Generated by Django 5.0.4 on 2024-05-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_graduateform_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateform',
            name='contactnum',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='graduateform',
            name='degree',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='graduateform',
            name='email_add',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='graduateform',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
    ]
