# Generated by Django 5.0.4 on 2024-05-20 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_graduateform_contactnum_graduateform_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateform',
            name='alumniID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.alumni'),
        ),
    ]
