# Generated by Django 5.0.4 on 2024-05-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_graduateform_alumniid'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='email_add',
            field=models.CharField(default='', max_length=100),
        ),
    ]
