# Generated by Django 5.0.4 on 2024-05-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alumni_email_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='degree',
            field=models.CharField(default='', max_length=100),
        ),
    ]
