# Generated by Django 5.0.4 on 2024-05-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alumni_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
    ]
