# Generated by Django 5.0.4 on 2024-05-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alumni_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduateform',
            old_name='streetaddress',
            new_name='alumniaddress',
        ),
    ]
