# Generated by Django 5.0.4 on 2024-05-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_rename_streetaddress_graduateform_alumniaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='claimed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
