# Generated by Django 5.0.4 on 2024-05-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alumni_claimed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
