# Generated by Django 5.0.3 on 2024-05-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alumni_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contactnum',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email_add',
            new_name='emailadd',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mi',
            new_name='middlename',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='year_level',
            new_name='yearlvl',
        ),
    ]
