# Generated by Django 5.0.4 on 2024-05-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_rename_contactnum_student_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateform',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
