# Generated by Django 5.0.4 on 2024-05-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_graduateform_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateform',
            name='meetingprofessional',
            field=models.CharField(default='', max_length=100),
        ),
    ]
