# Generated by Django 5.0.4 on 2024-05-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_graduateform_meetingprofessional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduateform',
            old_name='meetingprofessional',
            new_name='meetingprofessionalneeds',
        ),
    ]
