# Generated by Django 5.0.4 on 2024-05-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_rename_meetingprofessional_graduateform_meetingprofessionalneeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateform',
            name='opportunitiesabroad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='graduateform',
            name='personalitydevelopment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='graduateform',
            name='salaryimprovement',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='graduateform',
            name='technologiesvaluesformation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
