# Generated by Django 5.0.4 on 2024-05-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_graduateform_opportunitiesabroad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateform',
            name='academicprofession',
            field=models.IntegerField(),
        ),
    ]
