# Generated by Django 5.0.4 on 2024-05-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_graduateform_academicprofession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateform',
            name='communityfield',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='criticalskills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='globalfield',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='informationtechnologyskills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='learningefficiency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='opportunitiesabroad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='peopleskills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='personalitydevelopment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='problemsolvingskills',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='researchcapability',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='salaryimprovement',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='technologiesvaluesformation',
            field=models.IntegerField(),
        ),
    ]
