# Generated by Django 5.0.4 on 2024-05-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_graduateform_communityfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studID',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
