# Generated by Django 5.0.4 on 2024-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_student_studid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
