# Generated by Django 5.0.4 on 2024-05-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_student_studid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='yearlvl',
            field=models.CharField(max_length=10),
        ),
    ]
