# Generated by Django 5.0.4 on 2024-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_student_yearlvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lrn',
            field=models.CharField(max_length=12),
        ),
    ]
