# Generated by Django 5.0.4 on 2024-05-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_student_contact_student_degree_student_emailadd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emailadd',
        ),
        migrations.RemoveField(
            model_name='student',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='student',
            name='yearlvl',
        ),
    ]
