# Generated by Django 5.0.4 on 2024-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_remove_student_contact_remove_student_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
