# Generated by Django 5.0.4 on 2024-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_student_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middlename',
            field=models.CharField(default='', max_length=1),
        ),
    ]
