# Generated by Django 5.0.4 on 2024-05-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_student_yearlvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
    ]
