# Generated by Django 5.0.4 on 2024-05-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_student_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middlename',
            field=models.CharField(default='', max_length=50),
        ),
    ]
