# Generated by Django 5.0.4 on 2024-05-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_student_middlename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='emailadd',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='student',
            name='yearlvl',
        ),
    ]
