# Generated by Django 5.0.4 on 2024-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_student_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(default='', max_length=100),
        ),
    ]
