# Generated by Django 5.0.4 on 2024-05-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_student_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='yearlvl',
            field=models.CharField(default='', max_length=10),
        ),
    ]
