# Generated by Django 5.0.4 on 2024-05-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_student_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emailadd',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
