# Generated by Django 5.0.4 on 2024-06-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_rename_student_studentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfair',
            name='applicationdeadline',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='posted_date',
            field=models.DateField(default=None),
        ),
    ]
